In [1]:
import numpy as np
import pandas as pd 

In [2]:
pip install biobert-embedding==0.1.2 torch==1.2.0 -f https://download.pytorch.org/whl/torch_stable.html 

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 663.1MB 15kB/s 
     |████████████████████████████████| 133kB 3.1MB/s 
     |████████████████████████████████| 133kB 3.9MB/s 
     |████████████████████████████████| 7.7MB 370kB/s 
     |████████████████████████████████| 81kB 9.1MB/s 
  Created wheel for biobert-embedding: filename=biobert_embedding-0.1.2-cp37-none-any.whl size=5701 sha256=8acde718c0d9e74ccdeb573e730bed4681b5adff267c8c0ba73eb252fd52f2c4
  Stored in directory: /root/.cache/pip/wheels/ad/15/65/3fc6192a7cb7920672bb46d566173decb0875f35bbe03cd09d
Successfully built biobert-embedding
ERROR: torchvision 0.10.0+cu102 has requirement torch==1.9.0, but you'll have torch 1.2.0+cu92 which is incompatible.
ERROR: torchtext 0.10.0 has requirement torch==1.9.0, but you'll have torch 1.2.0+cu92 which is incompatible.
ERROR: botocore 1.20.100 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 1.24.3 which is incompat

In [3]:
from biobert_embedding.embedding import BiobertEmbedding 

In [4]:
biobert = BiobertEmbedding() 

/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is be

In [5]:
import nltk
nltk.download('stopwords') 
nltk.download('punkt' , quiet = True)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [6]:
result=pd.read_csv('/content/biobert_ade_preprocessed')

In [7]:
result

Unnamed: 0  ...                                 sentence embedding
0               0  ...  tensor([ 1.0630e-01, -1.7514e-01,  5.3981e-02,...
1               1  ...  tensor([ 1.2176e-01,  1.4887e-02,  5.3779e-02,...
2               2  ...  tensor([ 2.6735e-01, -4.6452e-01,  1.4280e-01,...
3               3  ...  tensor([ 2.1039e-01,  6.4826e-02,  1.5143e-01,...
4               4  ...  tensor([ 3.0714e-01,  5.2705e-02,  2.1322e-01,...
...           ...  ...                                                ...
23511       23511  ...  tensor([ 2.4703e-01, -6.7190e-02,  4.1837e-02,...
23512       23512  ...  tensor([ 3.3657e-01, -1.0307e-01,  7.6318e-02,...
23513       23513  ...  tensor([ 4.1880e-02, -8.3680e-02, -1.2667e-01,...
23514       23514  ...  tensor([ 1.5891e-01, -3.2259e-02,  1.4395e-01,...
23515       23515  ...  tensor([ 3.3168e-01, -1.5663e-01,  9.0562e-02,...

[23516 rows x 5 columns]

In [8]:
result.drop('Unnamed: 0' ,axis=1, inplace=True) 
result.drop('Unnamed: 0.1' ,axis=1, inplace=True)

In [9]:
result

observation  ...                                 sentence embedding
0      early phase ii semi double blind study of the ...  ...  tensor([ 1.0630e-01, -1.7514e-01,  5.3981e-02,...
1      cessation of mtx therapy led to complete regre...  ...  tensor([ 1.2176e-01,  1.4887e-02,  5.3779e-02,...
2      cutaneous biopsy showed hyphae and round inclu...  ...  tensor([ 2.6735e-01, -4.6452e-01,  1.4280e-01,...
3      she was treated with acyclovir and subsequentl...  ...  tensor([ 2.1039e-01,  6.4826e-02,  1.5143e-01,...
4      cisplatin was substituted and the patient achi...  ...  tensor([ 3.0714e-01,  5.2705e-02,  2.1322e-01,...
...                                                  ...  ...                                                ...
23511  ticlopidine induced aplastic anemia  two new c...  ...  tensor([ 2.4703e-01, -6.7190e-02,  4.1837e-02,...
23512  the risks of sumatriptan administration in pat...  ...  tensor([ 3.3657e-01, -1.0307e-01,  7.6318e-02,...
23513  however   the spectrum of hosts and clinical p...  ...  tensor([ 4.1880e-02, -8.3680e-02, -1.2667e-01,...
23514           antibiotic treatment should be continued  ...  tensor([ 1.5891e-01, -3.2259e-02,  1.4395e-01,...
23515  in case     a total daily dose of    mg sertra...  ...  tensor([ 3.3168e-01, -1.5663e-01,  9.0562e-02,...

[23516 rows x 3 columns]

In [10]:
def remove_tensor(str):
  str=str.replace('tensor','')
  str=str.replace('(','')
  str=str.replace(')','')
  str=str.replace(',','')
  str=str.replace('[','')
  str=str.replace(']','')
  return str


In [11]:
result

observation  ...                                 sentence embedding
0      early phase ii semi double blind study of the ...  ...  tensor([ 1.0630e-01, -1.7514e-01,  5.3981e-02,...
1      cessation of mtx therapy led to complete regre...  ...  tensor([ 1.2176e-01,  1.4887e-02,  5.3779e-02,...
2      cutaneous biopsy showed hyphae and round inclu...  ...  tensor([ 2.6735e-01, -4.6452e-01,  1.4280e-01,...
3      she was treated with acyclovir and subsequentl...  ...  tensor([ 2.1039e-01,  6.4826e-02,  1.5143e-01,...
4      cisplatin was substituted and the patient achi...  ...  tensor([ 3.0714e-01,  5.2705e-02,  2.1322e-01,...
...                                                  ...  ...                                                ...
23511  ticlopidine induced aplastic anemia  two new c...  ...  tensor([ 2.4703e-01, -6.7190e-02,  4.1837e-02,...
23512  the risks of sumatriptan administration in pat...  ...  tensor([ 3.3657e-01, -1.0307e-01,  7.6318e-02,...
23513  however   the spectrum of hosts and clinical p...  ...  tensor([ 4.1880e-02, -8.3680e-02, -1.2667e-01,...
23514           antibiotic treatment should be continued  ...  tensor([ 1.5891e-01, -3.2259e-02,  1.4395e-01,...
23515  in case     a total daily dose of    mg sertra...  ...  tensor([ 3.3168e-01, -1.5663e-01,  9.0562e-02,...

[23516 rows x 3 columns]

In [12]:

result['sentence embedding'] = result['sentence embedding'] .astype(str)


In [14]:
result['sentence embedding']=result['sentence embedding'].apply(remove_tensor)

In [15]:
result

observation  ...                                 sentence embedding
0      early phase ii semi double blind study of the ...  ...   1.0630e-01 -1.7514e-01  5.3981e-02  5.7100e-0...
1      cessation of mtx therapy led to complete regre...  ...   1.2176e-01  1.4887e-02  5.3779e-02 -2.0803e-0...
2      cutaneous biopsy showed hyphae and round inclu...  ...   2.6735e-01 -4.6452e-01  1.4280e-01 -7.3568e-0...
3      she was treated with acyclovir and subsequentl...  ...   2.1039e-01  6.4826e-02  1.5143e-01 -5.3155e-0...
4      cisplatin was substituted and the patient achi...  ...   3.0714e-01  5.2705e-02  2.1322e-01 -1.2713e-0...
...                                                  ...  ...                                                ...
23511  ticlopidine induced aplastic anemia  two new c...  ...   2.4703e-01 -6.7190e-02  4.1837e-02  1.5773e-0...
23512  the risks of sumatriptan administration in pat...  ...   3.3657e-01 -1.0307e-01  7.6318e-02  4.8204e-0...
23513  however   the spectrum of hosts and clinical p...  ...   4.1880e-02 -8.3680e-02 -1.2667e-01 -1.3184e-0...
23514           antibiotic treatment should be continued  ...   1.5891e-01 -3.2259e-02  1.4395e-01 -4.5586e-0...
23515  in case     a total daily dose of    mg sertra...  ...   3.3168e-01 -1.5663e-01  9.0562e-02 -2.7756e-0...

[23516 rows x 3 columns]

In [16]:
doc_vectors= pd.DataFrame(result['sentence embedding'].str.split().values.tolist())

In [17]:
doc_vectors['labels'] = result['labels'] 

In [18]:
doc_vectors 

0            1            2  ...          766          767 labels
0      1.0630e-01  -1.7514e-01   5.3981e-02  ...  -1.0725e-01   1.3992e-01      0
1      1.2176e-01   1.4887e-02   5.3779e-02  ...  -2.8833e-02  -1.6861e-01      0
2      2.6735e-01  -4.6452e-01   1.4280e-01  ...   2.0326e-01   1.6128e-02      0
3      2.1039e-01   6.4826e-02   1.5143e-01  ...  -1.2951e-02  -1.7454e-01      1
4      3.0714e-01   5.2705e-02   2.1322e-01  ...   6.3232e-02  -1.0560e-01      0
...           ...          ...          ...  ...          ...          ...    ...
23511  2.4703e-01  -6.7190e-02   4.1837e-02  ...  -9.5337e-02   3.7682e-02      1
23512  3.3657e-01  -1.0307e-01   7.6318e-02  ...  -4.0449e-01  -1.5660e-02      0
23513  4.1880e-02  -8.3680e-02  -1.2667e-01  ...   1.3097e-01  -5.9352e-02      0
23514  1.5891e-01  -3.2259e-02   1.4395e-01  ...   1.0493e-01   2.1687e-02      0
23515  3.3168e-01  -1.5663e-01   9.0562e-02  ...  -2.4800e-01   1.1627e-01      1

[23516 rows x 769 columns]

In [19]:
doc_vectors.to_csv('biobert_embeddings.csv')

In [20]:
doc_vectors = doc_vectors.dropna()

In [21]:
validation_data = doc_vectors.sample(frac = 0.2)
doc_vectors=doc_vectors.drop(validation_data.index) 

In [22]:
doc_vectors

0            1            2  ...          766          767 labels
0      1.0630e-01  -1.7514e-01   5.3981e-02  ...  -1.0725e-01   1.3992e-01      0
1      1.2176e-01   1.4887e-02   5.3779e-02  ...  -2.8833e-02  -1.6861e-01      0
2      2.6735e-01  -4.6452e-01   1.4280e-01  ...   2.0326e-01   1.6128e-02      0
3      2.1039e-01   6.4826e-02   1.5143e-01  ...  -1.2951e-02  -1.7454e-01      1
4      3.0714e-01   5.2705e-02   2.1322e-01  ...   6.3232e-02  -1.0560e-01      0
...           ...          ...          ...  ...          ...          ...    ...
23509  1.3018e-01  -1.4765e-01  -1.0680e-01  ...  -3.4465e-02   1.2192e-02      1
23511  2.4703e-01  -6.7190e-02   4.1837e-02  ...  -9.5337e-02   3.7682e-02      1
23512  3.3657e-01  -1.0307e-01   7.6318e-02  ...  -4.0449e-01  -1.5660e-02      0
23514  1.5891e-01  -3.2259e-02   1.4395e-01  ...   1.0493e-01   2.1687e-02      0
23515  3.3168e-01  -1.5663e-01   9.0562e-02  ...  -2.4800e-01   1.1627e-01      1

[18813 rows x 769 columns]

In [23]:
validation_data

0            1            2  ...          766          767 labels
13047  -5.9080e-02  -4.7542e-03   1.9866e-01  ...  -1.5681e-02   6.7305e-02      0
18173   1.0159e-01   4.1931e-02   2.0128e-01  ...   7.2802e-02  -9.1162e-02      1
13419   2.7329e-01  -5.5168e-02   5.3581e-02  ...   1.9184e-01  -5.4958e-02      0
8575   -9.7010e-02  -9.8612e-02   1.7006e-01  ...  -8.2762e-02  -4.4992e-02      0
19554   1.7452e-01  -1.1626e-01  -2.6528e-02  ...  -2.2325e-02  -8.2892e-02      0
...            ...          ...          ...  ...          ...          ...    ...
1191    1.3718e-01  -7.3950e-02   1.3494e-01  ...   1.4244e-03  -2.7034e-02      0
20335  -4.0952e-02   7.1508e-02   4.3508e-02  ...   8.5309e-02  -2.1759e-01      0
22719   2.8769e-02   4.9465e-02   9.2673e-02  ...  -1.1448e-01  -1.2985e-01      0
15182   6.8707e-02   7.6862e-02   1.4552e-01  ...  -3.3077e-01   2.0461e-03      1
21502  -2.0139e-02   3.5059e-02   7.9098e-02  ...   3.2049e-02  -1.0812e-01      0

[4703 rows x 769 columns]

In [24]:
x_val=validation_data.drop('labels' , axis=1) 
y_val=validation_data['labels']


In [26]:
x=doc_vectors.drop('labels' , axis=1)

In [27]:
y=doc_vectors['labels']

In [28]:
x.shape

(18813, 768)

In [29]:
y.shape

(18813,)

In [32]:
print(x.shape)
print(y.shape)
print(x_val.shape)
print(y_val.shape)

(18813, 768)
(18813,)
(4703, 768)
(4703,)


**DECISION TREE**

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dt_model= DecisionTreeClassifier(max_leaf_nodes=5)


In [33]:
dt_model.fit(x,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=5,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [34]:
dt_pred=dt_model.predict(x_val) 

In [35]:
dt_pred

array([0, 0, 0, ..., 0, 0, 1])

In [36]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [37]:
print(classification_report(y_val,dt_pred))

              precision    recall  f1-score   support

           0       0.80      0.89      0.85      3346
           1       0.64      0.46      0.54      1357

    accuracy                           0.77      4703
   macro avg       0.72      0.68      0.69      4703
weighted avg       0.76      0.77      0.76      4703



In [38]:
print(confusion_matrix(y_val,dt_pred))


[[2992  354]
 [ 727  630]]


In [40]:
#training accuracy 
dt_pred_train = dt_model.predict(x)
accuracy_score(y,dt_pred_train )  


0.7731887524584065

**RANDOM FOREST** 

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
rfc_model=RandomForestClassifier(n_estimators=1000,max_leaf_nodes=50)

In [43]:
rfc_model.fit(x,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=50, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
rfc_pred=rfc_model.predict(x_val)

In [45]:
print(classification_report(y_val,rfc_pred)) 

              precision    recall  f1-score   support

           0       0.81      0.98      0.89      3346
           1       0.90      0.43      0.59      1357

    accuracy                           0.82      4703
   macro avg       0.86      0.71      0.74      4703
weighted avg       0.84      0.82      0.80      4703



In [46]:
print(confusion_matrix(y_val,rfc_pred))

[[3284   62]
 [ 770  587]]


In [47]:
#training error 
rfc_train = rfc_model.predict(x)
accuracy_score(y,rfc_train) 

0.8476585339924521

**LOGISTIC REGRESSION**

In [48]:
 from sklearn.linear_model import LogisticRegression

In [49]:
log_model=LogisticRegression(max_iter=1000)

In [50]:
log_model.fit(x,y)       

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
log_pred=log_model.predict(x_val) 

In [52]:
log_pred

array([0, 1, 0, ..., 0, 0, 0])

In [53]:
print(classification_report(log_pred,y_val))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93      3380
           1       0.82      0.84      0.83      1323

    accuracy                           0.90      4703
   macro avg       0.88      0.89      0.88      4703
weighted avg       0.90      0.90      0.90      4703



In [54]:
print(confusion_matrix(log_pred,y_val))

[[3137  243]
 [ 209 1114]]


In [55]:
#calculate training accuracy
log_y_pred_train = log_model.predict(x) 
accuracy_score(y,log_y_pred_train) 

0.9220751607930686

**NAIVE BAYES MODELS**

In [56]:
from sklearn.naive_bayes import GaussianNB

In [57]:
gnb_model=GaussianNB()

In [58]:
gnb_model.fit(x,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [59]:
gnb_pred=gnb_model.predict(x_val) 

In [60]:
print(classification_report(y_val,gnb_pred)) 

              precision    recall  f1-score   support

           0       0.93      0.75      0.83      3346
           1       0.58      0.86      0.69      1357

    accuracy                           0.78      4703
   macro avg       0.75      0.80      0.76      4703
weighted avg       0.83      0.78      0.79      4703



In [61]:
print(confusion_matrix(y_val,gnb_pred))

[[2507  839]
 [ 194 1163]]


In [62]:
#calculate training error 
log_y_pred_train = log_model.predict(x) 
accuracy_score(y,log_y_pred_train) 

0.9220751607930686

**XG BOOST**

In [63]:
from xgboost import XGBClassifier 

In [65]:
xgb_model=XGBClassifier() 
xgb_model.fit(x.values,y.values) 

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [75]:
xgb_pred = xgb_model.predict(x_val.values)

In [76]:
print(classification_report(y_val,xgb_pred)) 

              precision    recall  f1-score   support

           0       0.90      0.93      0.91      3346
           1       0.81      0.74      0.77      1357

    accuracy                           0.87      4703
   macro avg       0.85      0.83      0.84      4703
weighted avg       0.87      0.87      0.87      4703



In [78]:
print(confusion_matrix(y_val,xgb_pred)) 

[[3108  238]
 [ 359  998]]


In [79]:
#training accuracy 
xgb_pred_train = xgb_model.predict(x.values) 
accuracy_score(y,xgb_pred_train)   

0.9037367777600596

In [80]:
#no of positive and negative in training data 

zerocount=0
onecount=0
for i in y:
  if i == 0:
    zerocount+=1
  else:
    onecount+=1
print("no of negative sample in training class is:",zerocount)
print("no of positive sample in training class is:",onecount) 

no of negative sample in training class is: 13349
no of positive sample in training class is: 5464
