In [1]:
import numpy as np
import pandas as pd 

In [2]:
pip install biobert-embedding==0.1.2 torch==1.2.0 -f https://download.pytorch.org/whl/torch_stable.html 

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [3]:
from biobert_embedding.embedding import BiobertEmbedding 

In [4]:
biobert = BiobertEmbedding() 

In [5]:
import nltk
nltk.download('stopwords') 
nltk.download('punkt' , quiet = True)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
result=pd.read_csv('/content/biobert_ade_preprocessed')

In [7]:
result

Unnamed: 0  ...                                 sentence embedding
0               0  ...  tensor([ 1.0630e-01, -1.7514e-01,  5.3981e-02,...
1               1  ...  tensor([ 1.2176e-01,  1.4887e-02,  5.3779e-02,...
2               2  ...  tensor([ 2.6735e-01, -4.6452e-01,  1.4280e-01,...
3               3  ...  tensor([ 2.1039e-01,  6.4826e-02,  1.5143e-01,...
4               4  ...  tensor([ 3.0714e-01,  5.2705e-02,  2.1322e-01,...
...           ...  ...                                                ...
23511       23511  ...  tensor([ 2.4703e-01, -6.7190e-02,  4.1837e-02,...
23512       23512  ...  tensor([ 3.3657e-01, -1.0307e-01,  7.6318e-02,...
23513       23513  ...  tensor([ 4.1880e-02, -8.3680e-02, -1.2667e-01,...
23514       23514  ...  tensor([ 1.5891e-01, -3.2259e-02,  1.4395e-01,...
23515       23515  ...  tensor([ 3.3168e-01, -1.5663e-01,  9.0562e-02,...

[23516 rows x 5 columns]

In [8]:
result.drop('Unnamed: 0' ,axis=1, inplace=True) 
result.drop('Unnamed: 0.1' ,axis=1, inplace=True)

In [9]:
result

observation  ...                                 sentence embedding
0      early phase ii semi double blind study of the ...  ...  tensor([ 1.0630e-01, -1.7514e-01,  5.3981e-02,...
1      cessation of mtx therapy led to complete regre...  ...  tensor([ 1.2176e-01,  1.4887e-02,  5.3779e-02,...
2      cutaneous biopsy showed hyphae and round inclu...  ...  tensor([ 2.6735e-01, -4.6452e-01,  1.4280e-01,...
3      she was treated with acyclovir and subsequentl...  ...  tensor([ 2.1039e-01,  6.4826e-02,  1.5143e-01,...
4      cisplatin was substituted and the patient achi...  ...  tensor([ 3.0714e-01,  5.2705e-02,  2.1322e-01,...
...                                                  ...  ...                                                ...
23511  ticlopidine induced aplastic anemia  two new c...  ...  tensor([ 2.4703e-01, -6.7190e-02,  4.1837e-02,...
23512  the risks of sumatriptan administration in pat...  ...  tensor([ 3.3657e-01, -1.0307e-01,  7.6318e-02,...
23513  however   the spectrum of hosts and clinical p...  ...  tensor([ 4.1880e-02, -8.3680e-02, -1.2667e-01,...
23514           antibiotic treatment should be continued  ...  tensor([ 1.5891e-01, -3.2259e-02,  1.4395e-01,...
23515  in case     a total daily dose of    mg sertra...  ...  tensor([ 3.3168e-01, -1.5663e-01,  9.0562e-02,...

[23516 rows x 3 columns]

In [10]:
def remove_tensor(str):
  str=str.replace('tensor','')
  str=str.replace('(','')
  str=str.replace(')','')
  str=str.replace(',','')
  str=str.replace('[','')
  str=str.replace(']','')
  return str


In [11]:
result

observation  ...                                 sentence embedding
0      early phase ii semi double blind study of the ...  ...  tensor([ 1.0630e-01, -1.7514e-01,  5.3981e-02,...
1      cessation of mtx therapy led to complete regre...  ...  tensor([ 1.2176e-01,  1.4887e-02,  5.3779e-02,...
2      cutaneous biopsy showed hyphae and round inclu...  ...  tensor([ 2.6735e-01, -4.6452e-01,  1.4280e-01,...
3      she was treated with acyclovir and subsequentl...  ...  tensor([ 2.1039e-01,  6.4826e-02,  1.5143e-01,...
4      cisplatin was substituted and the patient achi...  ...  tensor([ 3.0714e-01,  5.2705e-02,  2.1322e-01,...
...                                                  ...  ...                                                ...
23511  ticlopidine induced aplastic anemia  two new c...  ...  tensor([ 2.4703e-01, -6.7190e-02,  4.1837e-02,...
23512  the risks of sumatriptan administration in pat...  ...  tensor([ 3.3657e-01, -1.0307e-01,  7.6318e-02,...
23513  however   the spectrum of hosts and clinical p...  ...  tensor([ 4.1880e-02, -8.3680e-02, -1.2667e-01,...
23514           antibiotic treatment should be continued  ...  tensor([ 1.5891e-01, -3.2259e-02,  1.4395e-01,...
23515  in case     a total daily dose of    mg sertra...  ...  tensor([ 3.3168e-01, -1.5663e-01,  9.0562e-02,...

[23516 rows x 3 columns]

In [12]:

result['sentence embedding'] = result['sentence embedding'] .astype(str)


In [13]:
result['sentence embedding']=result['sentence embedding'].apply(remove_tensor)

In [14]:
result

observation  ...                                 sentence embedding
0      early phase ii semi double blind study of the ...  ...   1.0630e-01 -1.7514e-01  5.3981e-02  5.7100e-0...
1      cessation of mtx therapy led to complete regre...  ...   1.2176e-01  1.4887e-02  5.3779e-02 -2.0803e-0...
2      cutaneous biopsy showed hyphae and round inclu...  ...   2.6735e-01 -4.6452e-01  1.4280e-01 -7.3568e-0...
3      she was treated with acyclovir and subsequentl...  ...   2.1039e-01  6.4826e-02  1.5143e-01 -5.3155e-0...
4      cisplatin was substituted and the patient achi...  ...   3.0714e-01  5.2705e-02  2.1322e-01 -1.2713e-0...
...                                                  ...  ...                                                ...
23511  ticlopidine induced aplastic anemia  two new c...  ...   2.4703e-01 -6.7190e-02  4.1837e-02  1.5773e-0...
23512  the risks of sumatriptan administration in pat...  ...   3.3657e-01 -1.0307e-01  7.6318e-02  4.8204e-0...
23513  however   the spectrum of hosts and clinical p...  ...   4.1880e-02 -8.3680e-02 -1.2667e-01 -1.3184e-0...
23514           antibiotic treatment should be continued  ...   1.5891e-01 -3.2259e-02  1.4395e-01 -4.5586e-0...
23515  in case     a total daily dose of    mg sertra...  ...   3.3168e-01 -1.5663e-01  9.0562e-02 -2.7756e-0...

[23516 rows x 3 columns]

In [15]:
doc_vectors= pd.DataFrame(result['sentence embedding'].str.split().values.tolist())

In [16]:
doc_vectors['labels'] = result['labels'] 

In [17]:
doc_vectors 

0            1            2  ...          766          767 labels
0      1.0630e-01  -1.7514e-01   5.3981e-02  ...  -1.0725e-01   1.3992e-01      0
1      1.2176e-01   1.4887e-02   5.3779e-02  ...  -2.8833e-02  -1.6861e-01      0
2      2.6735e-01  -4.6452e-01   1.4280e-01  ...   2.0326e-01   1.6128e-02      0
3      2.1039e-01   6.4826e-02   1.5143e-01  ...  -1.2951e-02  -1.7454e-01      1
4      3.0714e-01   5.2705e-02   2.1322e-01  ...   6.3232e-02  -1.0560e-01      0
...           ...          ...          ...  ...          ...          ...    ...
23511  2.4703e-01  -6.7190e-02   4.1837e-02  ...  -9.5337e-02   3.7682e-02      1
23512  3.3657e-01  -1.0307e-01   7.6318e-02  ...  -4.0449e-01  -1.5660e-02      0
23513  4.1880e-02  -8.3680e-02  -1.2667e-01  ...   1.3097e-01  -5.9352e-02      0
23514  1.5891e-01  -3.2259e-02   1.4395e-01  ...   1.0493e-01   2.1687e-02      0
23515  3.3168e-01  -1.5663e-01   9.0562e-02  ...  -2.4800e-01   1.1627e-01      1

[23516 rows x 769 columns]

In [18]:
doc_vectors.to_csv('biobert_embeddings.csv')

In [19]:
doc_vectors = doc_vectors.dropna()

In [20]:
validation_data = doc_vectors.sample(frac = 0.2)
doc_vectors=doc_vectors.drop(validation_data.index) 

In [21]:
doc_vectors

0            1            2  ...          766          767 labels
0      1.0630e-01  -1.7514e-01   5.3981e-02  ...  -1.0725e-01   1.3992e-01      0
1      1.2176e-01   1.4887e-02   5.3779e-02  ...  -2.8833e-02  -1.6861e-01      0
2      2.6735e-01  -4.6452e-01   1.4280e-01  ...   2.0326e-01   1.6128e-02      0
3      2.1039e-01   6.4826e-02   1.5143e-01  ...  -1.2951e-02  -1.7454e-01      1
5      2.2129e-01   1.3302e-01   6.9349e-02  ...   1.1662e-01   5.1704e-02      0
...           ...          ...          ...  ...          ...          ...    ...
23511  2.4703e-01  -6.7190e-02   4.1837e-02  ...  -9.5337e-02   3.7682e-02      1
23512  3.3657e-01  -1.0307e-01   7.6318e-02  ...  -4.0449e-01  -1.5660e-02      0
23513  4.1880e-02  -8.3680e-02  -1.2667e-01  ...   1.3097e-01  -5.9352e-02      0
23514  1.5891e-01  -3.2259e-02   1.4395e-01  ...   1.0493e-01   2.1687e-02      0
23515  3.3168e-01  -1.5663e-01   9.0562e-02  ...  -2.4800e-01   1.1627e-01      1

[18813 rows x 769 columns]

In [22]:
validation_data

0            1            2  ...          766          767 labels
17066   3.0262e-01  -1.7107e-01  -1.1653e-01  ...  -1.6954e-01  -1.3577e-01      1
14326   1.1004e-01  -3.3209e-01   8.8760e-02  ...  -9.8049e-02  -1.7382e-01      1
21648   1.1525e-01   1.4990e-01  -3.1544e-02  ...   2.7972e-02  -1.2512e-01      0
8543    3.6241e-01   2.4577e-01   5.6661e-02  ...   5.6734e-01   6.4272e-02      0
18555   9.5679e-02  -2.1951e-01   1.1943e-01  ...   3.5840e-01  -3.2365e-01      0
...            ...          ...          ...  ...          ...          ...    ...
21563   2.3687e-01   3.4515e-02   2.1258e-01  ...   2.2738e-01  -1.7688e-01      0
2681    1.9311e-01   1.7783e-02   1.3710e-01  ...   5.3960e-02  -8.4925e-02      1
4758   -1.2907e-01  -3.4750e-01  -4.9775e-02  ...  -5.4405e-02   1.3010e-01      0
22326   5.2560e-02  -9.8982e-02  -9.0276e-02  ...   1.6802e-01   4.2655e-03      0
3458   -8.7331e-02  -6.7684e-02  -7.4912e-02  ...  -6.3076e-02   8.2475e-02      0

[4703 rows x 769 columns]

In [23]:
x_val=validation_data.drop('labels' , axis=1) 
y_val=validation_data['labels']


In [24]:
x=doc_vectors.drop('labels' , axis=1)

In [25]:
y=doc_vectors['labels']

In [26]:
x.shape

(18813, 768)

In [27]:
y.shape

(18813,)

**SMOTE**

In [28]:
from imblearn.over_sampling import SMOTE 

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [29]:
smote = SMOTE(random_state = 2021)
x, y = smote.fit_resample(x,y)  

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [30]:
print(x.shape)
print(y.shape)
print(x_val.shape)
print(y_val.shape)

(26804, 768)
(26804,)
(4703, 768)
(4703,)


**DECISION TREE**

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
dt_model= DecisionTreeClassifier(max_leaf_nodes=5)


In [33]:
dt_model.fit(x,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=5,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [34]:
dt_pred=dt_model.predict(x_val) 

In [35]:
dt_pred

array([0, 1, 1, ..., 0, 0, 0])

In [36]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score


In [37]:
print(classification_report(y_val,dt_pred))

              precision    recall  f1-score   support

           0       0.86      0.71      0.78      3293
           1       0.52      0.73      0.61      1410

    accuracy                           0.72      4703
   macro avg       0.69      0.72      0.69      4703
weighted avg       0.76      0.72      0.73      4703



In [38]:
print(confusion_matrix(y_val,dt_pred))


[[2341  952]
 [ 378 1032]]


In [39]:
#training accuracy 
dt_pred_train = dt_model.predict(x)
accuracy_score(y,dt_pred_train )  


0.7333606924339651

**RANDOM FOREST** 

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [41]:
rfc_model=RandomForestClassifier(n_estimators=1000,max_leaf_nodes=50)

In [42]:
rfc_model.fit(x,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=50, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [43]:
rfc_pred=rfc_model.predict(x_val)

In [44]:
print(classification_report(y_val,rfc_pred)) 

              precision    recall  f1-score   support

           0       0.92      0.87      0.89      3293
           1       0.74      0.81      0.77      1410

    accuracy                           0.86      4703
   macro avg       0.83      0.84      0.83      4703
weighted avg       0.86      0.86      0.86      4703



In [45]:
print(confusion_matrix(y_val,rfc_pred))

[[2881  412]
 [ 267 1143]]


In [46]:
#training error 
rfc_train = rfc_model.predict(x)
accuracy_score(y,rfc_train) 

0.8967691389344874

**LOGISTIC REGRESSION**

In [47]:
 from sklearn.linear_model import LogisticRegression

In [48]:
log_model=LogisticRegression(max_iter=1000)

In [49]:
log_model.fit(x,y)       

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [50]:
log_pred=log_model.predict(x_val) 

In [51]:
log_pred

array([1, 1, 0, ..., 0, 0, 0])

In [52]:
print(classification_report(log_pred,y_val))

              precision    recall  f1-score   support

           0       0.91      0.95      0.93      3133
           1       0.89      0.80      0.84      1570

    accuracy                           0.90      4703
   macro avg       0.90      0.88      0.89      4703
weighted avg       0.90      0.90      0.90      4703



In [53]:
print(confusion_matrix(log_pred,y_val))

[[2981  152]
 [ 312 1258]]


In [54]:
#calculate training accuracy
log_y_pred_train = log_model.predict(x) 
accuracy_score(y,log_y_pred_train) 

0.9250111923593494

**NAIVE BAYES MODELS**

In [55]:
from sklearn.naive_bayes import GaussianNB

In [56]:
gnb_model=GaussianNB()

In [57]:
gnb_model.fit(x,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [58]:
gnb_pred=gnb_model.predict(x_val) 

In [59]:
print(classification_report(y_val,gnb_pred)) 

              precision    recall  f1-score   support

           0       0.90      0.79      0.84      3293
           1       0.61      0.80      0.69      1410

    accuracy                           0.79      4703
   macro avg       0.76      0.79      0.77      4703
weighted avg       0.81      0.79      0.80      4703



In [60]:
print(confusion_matrix(y_val,gnb_pred))

[[2589  704]
 [ 286 1124]]


In [61]:
#calculate training error 
log_y_pred_train = log_model.predict(x) 
accuracy_score(y,log_y_pred_train) 

0.9250111923593494

**XG BOOST**

In [62]:
from xgboost import XGBClassifier 

In [64]:
xgb_model=XGBClassifier() 
xgb_model.fit(x,y) 

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [65]:
xgb_pred = xgb_model.predict(x_val.values)

In [66]:
print(classification_report(y_val,xgb_pred)) 

              precision    recall  f1-score   support

           0       0.94      0.87      0.90      3293
           1       0.74      0.88      0.80      1410

    accuracy                           0.87      4703
   macro avg       0.84      0.87      0.85      4703
weighted avg       0.88      0.87      0.87      4703



In [67]:
print(confusion_matrix(y_val,xgb_pred))  

[[2852  441]
 [ 175 1235]]


In [69]:
#training accuracy 
xgb_pred_train = xgb_model.predict(x) 
accuracy_score(y,xgb_pred_train)   

0.9154603790479033

In [70]:
#no of positive and negative in training data 

zerocount=0
onecount=0
for i in y:
  if i == 0:
    zerocount+=1
  else:
    onecount+=1
print("no of negative sample in training class is:",zerocount)
print("no of positive sample in training class is:",onecount) 

no of negative sample in training class is: 13402
no of positive sample in training class is: 13402
