In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
from keras.models import Sequential 
from keras.layers import Dense, Embedding, GRU, LSTM
from keras.layers.embeddings import Embedding
from keras.initializers import Constant
from keras.callbacks import ModelCheckpoint
from keras.models import load_model

In [ ]:
result=pd.read_csv('/content/preprocessed_ade.csv')

In [ ]:
result

Unnamed: 0                                        observation  labels
0           12606  early phase ii semi double blind study of the ...       0
1             685  cessation of mtx therapy led to complete regre...       0
2            5127  cutaneous biopsy showed hyphae and round inclu...       0
3            3158  she was treated with acyclovir and subsequentl...       1
4           10685  cisplatin was substituted and the patient achi...       0
...           ...                                                ...     ...
23511         982  ticlopidine induced aplastic anemia  two new c...       1
23512       14487  the risks of sumatriptan administration in pat...       0
23513        4680  however   the spectrum of hosts and clinical p...       0
23514        2588           antibiotic treatment should be continued       0
23515        6571  in case     a total daily dose of    mg sertra...       1

[23516 rows x 3 columns]

In [ ]:
import gensim
import os
import nltk

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


In [ ]:
result.drop('Unnamed: 0' , axis = 1, inplace = True)

In [ ]:
result

observation  labels
0      early phase ii semi double blind study of the ...       0
1      cessation of mtx therapy led to complete regre...       0
2      cutaneous biopsy showed hyphae and round inclu...       0
3      she was treated with acyclovir and subsequentl...       1
4      cisplatin was substituted and the patient achi...       0
...                                                  ...     ...
23511  ticlopidine induced aplastic anemia  two new c...       1
23512  the risks of sumatriptan administration in pat...       0
23513  however   the spectrum of hosts and clinical p...       0
23514           antibiotic treatment should be continued       0
23515  in case     a total daily dose of    mg sertra...       1

[23516 rows x 2 columns]

In [ ]:
!wget -P /root/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2021-06-24 17:09:14--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.76.102
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.76.102|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.



In [ ]:
url="https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

In [ ]:
embeddings = gensim.models.KeyedVectors.load_word2vec_format(url, binary=True) 

In [ ]:
docs_vectors = pd.DataFrame() # creating empty final dataframe
stopwords = nltk.corpus.stopwords.words('english') # removing stop words  
for doc in result['observation'].str.lower().str.replace('[^a-z ]', ''): # looping through each document and cleaning it
    temp = pd.DataFrame()  # creating a temporary dataframe(store value for 1st doc & for 2nd doc remove the details of 1st & proced through 2nd and so on..)
    for word in doc.split(' '): # looping through each word of a single document and spliting through space
        if word not in stopwords: # if word is not present in stopwords then (try)
            try:
                word_vec = embeddings[word] # if word is present in embeddings(goole provides weights associate with words(300)) then proceed
                temp = temp.append(pd.Series(word_vec), ignore_index = True) # if word is present then append it to temporary dataframe
            except:
                pass
    doc_vector = temp.mean() # take the average of each column(w0, w1, w2,........w300)
    docs_vectors = docs_vectors.append(doc_vector, ignore_index = True) # append each document value to the final dataframe
docs_vectors.shape

(23516, 300)

In [ ]:
docs_vectors['labels'] = result['labels'] 

In [ ]:
docs_vectors = docs_vectors.dropna()

In [ ]:
docs_vectors

0         1         2  ...       298       299  labels
0     -0.050695 -0.013357 -0.008664  ... -0.025411  0.035197       0
1     -0.003021  0.127523  0.022970  ...  0.129150  0.039032       0
2     -0.029696  0.117454  0.070279  ...  0.084306  0.066426       0
3     -0.034995  0.044120  0.062256  ...  0.183340 -0.034546       1
4      0.015993  0.063070 -0.002374  ...  0.117784  0.017456       0
...         ...       ...       ...  ...       ...       ...     ...
23511 -0.037612 -0.003371 -0.043265  ...  0.091285  0.045650       1
23512  0.003700  0.071014 -0.004820  ...  0.142891  0.104774       0
23513 -0.051111  0.146917 -0.019682  ...  0.156669  0.086036       0
23514 -0.108724  0.262695 -0.012207  ...  0.284668  0.115234       0
23515 -0.116017  0.087541  0.000201  ...  0.140864  0.032995       1

[23508 rows x 301 columns]

In [ ]:
validation_data = docs_vectors.sample(frac = 0.2)
docs_vectors=docs_vectors.drop(validation_data.index) 

In [ ]:
validation_data

0         1         2  ...       298       299  labels
15265  0.012791  0.084262  0.028987  ...  0.145923  0.072852       1
8002  -0.089577  0.045266  0.057151  ...  0.090959  0.029261       0
21718 -0.000244  0.122955  0.074524  ...  0.268677  0.114075       1
11924 -0.073042  0.000433  0.055775  ...  0.102800  0.070157       1
9999   0.058792  0.165047 -0.046371  ...  0.223495  0.092110       0
...         ...       ...       ...  ...       ...       ...     ...
20385 -0.039185  0.108532 -0.036333  ...  0.135182  0.044533       0
123   -0.060951  0.098073 -0.047083  ...  0.172289  0.055923       0
17213 -0.106824  0.064709 -0.001605  ...  0.136332  0.076876       1
15649 -0.130005  0.252431  0.070312  ...  0.243266  0.105967       1
7046  -0.029419  0.264496 -0.007629  ...  0.140076  0.094360       0

[4702 rows x 301 columns]

In [ ]:
x_val=validation_data.drop('labels' , axis=1) 
y_val=validation_data['labels']


In [ ]:
x_val

0         1         2    ...       297       298       299
15265  0.012791  0.084262  0.028987  ... -0.006445  0.145923  0.072852
8002  -0.089577  0.045266  0.057151  ... -0.006001  0.090959  0.029261
21718 -0.000244  0.122955  0.074524  ...  0.276611  0.268677  0.114075
11924 -0.073042  0.000433  0.055775  ... -0.015148  0.102800  0.070157
9999   0.058792  0.165047 -0.046371  ...  0.128531  0.223495  0.092110
...         ...       ...       ...  ...       ...       ...       ...
20385 -0.039185  0.108532 -0.036333  ...  0.110363  0.135182  0.044533
123   -0.060951  0.098073 -0.047083  ...  0.156611  0.172289  0.055923
17213 -0.106824  0.064709 -0.001605  ...  0.078470  0.136332  0.076876
15649 -0.130005  0.252431  0.070312  ...  0.126689  0.243266  0.105967
7046  -0.029419  0.264496 -0.007629  ...  0.042702  0.140076  0.094360

[4702 rows x 300 columns]

In [ ]:
y_val

15265    1
8002     0
21718    1
11924    1
9999     0
        ..
20385    0
123      0
17213    1
15649    1
7046     0
Name: labels, Length: 4702, dtype: int64

In [ ]:
print(x_val.shape)
print(y_val.shape)

(4702, 300)
(4702,)


In [ ]:
from sklearn.model_selection import train_test_split 

In [ ]:
x=docs_vectors.drop('labels' , axis=1)
y=docs_vectors['labels']

In [ ]:
print(x.shape)
print(y.shape)

(18806, 300)
(18806,)


In [ ]:
from imblearn.over_sampling import SMOTE

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
smote = SMOTE(random_state = 2021)
x, y = smote.fit_resample(x,y) 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
print(x.shape)
print(y.shape)
print(x_val.shape)
print(y_val.shape) 

(26732, 300)
(26732,)
(4702, 300)
(4702,)


In [ ]:
zerocount=0
onecount=0
for i in y:
  if i == 0:
    zerocount+=1
  else:
    onecount+=1
print("no of negative sample in training class is:",zerocount)
print("no of positive sample in training class is:",onecount) 

no of negative sample in training class is: 13366
no of positive sample in training class is: 13366


**DECISION TREE**

In [ ]:
from sklearn.tree import DecisionTreeClassifier


In [ ]:
dt_model= DecisionTreeClassifier(max_depth=5)  

In [ ]:
dt_model.fit(x,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dt_pred=dt_model.predict(x_val)

In [ ]:
dt_pred

array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [ ]:
print(classification_report(y_val,dt_pred))

              precision    recall  f1-score   support

           0       0.87      0.62      0.73      3321
           1       0.46      0.77      0.58      1381

    accuracy                           0.67      4702
   macro avg       0.66      0.70      0.65      4702
weighted avg       0.75      0.67      0.68      4702



In [ ]:
print(confusion_matrix(y_val,dt_pred))

[[2074 1247]
 [ 314 1067]]


In [ ]:
#training error 
dt_pred_train = dt_model.predict(x)
accuracy_score(y,dt_pred_train )  


0.7277046236720036

**LOGISTIC REGRESSION** 

In [ ]:
 from sklearn.linear_model import LogisticRegression

In [ ]:
log_model=LogisticRegression(max_iter=1000)

In [ ]:
log_model.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
log_pred=log_model.predict(x_val)

In [ ]:
log_pred

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
print(classification_report(log_pred,y_val))

              precision    recall  f1-score   support

           0       0.77      0.89      0.83      2892
           1       0.76      0.58      0.66      1810

    accuracy                           0.77      4702
   macro avg       0.77      0.74      0.74      4702
weighted avg       0.77      0.77      0.76      4702



In [ ]:
print(confusion_matrix(log_pred,y_val))

[[2567  325]
 [ 754 1056]]


In [ ]:
#calculate training error 
log_y_pred_train = log_model.predict(x) 
accuracy_score(y,log_y_pred_train) 

0.7909621427502619

**NAIVE BAYES MODELS**

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb_model=GaussianNB()


In [ ]:
gnb_model.fit(x,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
gnb_pred=gnb_model.predict(x_val)

In [ ]:
print(classification_report(y_val,gnb_pred))

              precision    recall  f1-score   support

           0       0.87      0.70      0.77      3321
           1       0.50      0.74      0.60      1381

    accuracy                           0.71      4702
   macro avg       0.68      0.72      0.69      4702
weighted avg       0.76      0.71      0.72      4702



In [ ]:
print(confusion_matrix(y_val,gnb_pred))

[[2316 1005]
 [ 361 1020]]


In [ ]:
#training error 
gnb_train_pred = gnb_model.predict(x)
accuracy_score(y,gnb_train_pred) 

0.7649633398174472

**RANDOM FOREST CLASSIFIER**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc_model=RandomForestClassifier(n_estimators=1000,max_leaf_nodes=50)

In [ ]:
rfc_model.fit(x,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=50, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rfc_pred=rfc_model.predict(x_val)

In [ ]:
print(classification_report(y_val,rfc_pred))

              precision    recall  f1-score   support

           0       0.88      0.85      0.87      3321
           1       0.67      0.71      0.69      1381

    accuracy                           0.81      4702
   macro avg       0.77      0.78      0.78      4702
weighted avg       0.82      0.81      0.81      4702



In [ ]:
print(confusion_matrix(y_val,rfc_pred))

[[2838  483]
 [ 396  985]]


In [ ]:
#training error 
rfc_train = rfc_model.predict(x)
accuracy_score(y,rfc_train) 

0.8482343259015412

**XG BOOST**

In [ ]:
pip install xgboost 

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_model=XGBClassifier()

In [ ]:
xgb_model.fit(x,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
xgb_pred = xgb_model.predict(x_val.values)


In [ ]:
print(classification_report(y_val,xgb_pred))

              precision    recall  f1-score   support

           0       0.91      0.82      0.86      3321
           1       0.65      0.80      0.72      1381

    accuracy                           0.82      4702
   macro avg       0.78      0.81      0.79      4702
weighted avg       0.83      0.82      0.82      4702



In [ ]:
print(confusion_matrix(y_val,xgb_pred)) 

[[2735  586]
 [ 280 1101]]


In [ ]:
#training error 
xgb_pred_train = xgb_model.predict(x) 
accuracy_score(y,xgb_pred_train)   

0.871090827472692