In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
data=pd.read_csv('/content/preprocessed_ade.csv')

In [ ]:
data

Unnamed: 0                                        observation  labels
0           12606  early phase ii semi double blind study of the ...       0
1             685  cessation of mtx therapy led to complete regre...       0
2            5127  cutaneous biopsy showed hyphae and round inclu...       0
3            3158  she was treated with acyclovir and subsequentl...       1
4           10685  cisplatin was substituted and the patient achi...       0
...           ...                                                ...     ...
23511         982  ticlopidine induced aplastic anemia  two new c...       1
23512       14487  the risks of sumatriptan administration in pat...       0
23513        4680  however   the spectrum of hosts and clinical p...       0
23514        2588           antibiotic treatment should be continued       0
23515        6571  in case     a total daily dose of    mg sertra...       1

[23516 rows x 3 columns]

In [ ]:
import gensim
import os
import nltk

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


In [ ]:
data

Unnamed: 0                                        observation  labels
0           12606  early phase ii semi double blind study of the ...       0
1             685  cessation of mtx therapy led to complete regre...       0
2            5127  cutaneous biopsy showed hyphae and round inclu...       0
3            3158  she was treated with acyclovir and subsequentl...       1
4           10685  cisplatin was substituted and the patient achi...       0
...           ...                                                ...     ...
23511         982  ticlopidine induced aplastic anemia  two new c...       1
23512       14487  the risks of sumatriptan administration in pat...       0
23513        4680  however   the spectrum of hosts and clinical p...       0
23514        2588           antibiotic treatment should be continued       0
23515        6571  in case     a total daily dose of    mg sertra...       1

[23516 rows x 3 columns]

In [ ]:
!wget -P /root/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2021-06-24 07:28:42--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.154.38
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.154.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘/root/input/GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  55.5MB/s    in 30s     

2021-06-24 07:29:13 (52.3 MB/s) - ‘/root/input/GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]



In [ ]:
url="https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

In [ ]:
embeddings = gensim.models.KeyedVectors.load_word2vec_format(url, binary=True)

In [ ]:
docs_vectors = pd.DataFrame() # creating empty final dataframe
stopwords = nltk.corpus.stopwords.words('english') # removing stop words
for doc in data['observation'].str.lower().str.replace('[^a-z ]', ''): # looping through each document and cleaning it
    temp = pd.DataFrame()  # creating a temporary dataframe(store value for 1st doc & for 2nd doc remove the details of 1st & proced through 2nd and so on..)
    for word in doc.split(' '): # looping through each word of a single document and spliting through space
        if word not in stopwords: # if word is not present in stopwords then (try)
            try:
                word_vec = embeddings[word] # if word is present in embeddings(goole provides weights associate with words(300)) then proceed
                temp = temp.append(pd.Series(word_vec), ignore_index = True) # if word is present then append it to temporary dataframe
            except:
                pass
    doc_vector = temp.mean() # take the average of each column(w0, w1, w2,........w300)
    docs_vectors = docs_vectors.append(doc_vector, ignore_index = True) # append each document value to the final dataframe
docs_vectors.shape

(23516, 300)

In [ ]:
 docs_vectors['labels'] = data['labels']

In [ ]:
docs_vectors = docs_vectors.dropna()

In [ ]:
docs_vectors

0         1         2  ...       298       299  labels
0     -0.050695 -0.013357 -0.008664  ... -0.025411  0.035197       0
1     -0.003021  0.127523  0.022970  ...  0.129150  0.039032       0
2     -0.029696  0.117454  0.070279  ...  0.084306  0.066426       0
3     -0.034995  0.044120  0.062256  ...  0.183340 -0.034546       1
4      0.015993  0.063070 -0.002374  ...  0.117784  0.017456       0
...         ...       ...       ...  ...       ...       ...     ...
23511 -0.037612 -0.003371 -0.043265  ...  0.091285  0.045650       1
23512  0.003700  0.071014 -0.004820  ...  0.142891  0.104774       0
23513 -0.051111  0.146917 -0.019682  ...  0.156669  0.086036       0
23514 -0.108724  0.262695 -0.012207  ...  0.284668  0.115234       0
23515 -0.116017  0.087541  0.000201  ...  0.140864  0.032995       1

[23508 rows x 301 columns]

In [ ]:
from sklearn.model_selection import train_test_split 

In [ ]:
x=docs_vectors.drop('labels' , axis=1)

In [ ]:
y=docs_vectors['labels']

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2 , random_state=2021)

In [ ]:
zerocount=0
onecount=0
for i in y_train:
  if i == 0:
    zerocount+=1
  else:
    onecount+=1
print("no of negative sample in training class is:",zerocount)
print("no of positive sample in training class is:",onecount) 

no of negative sample in training class is: 13328
no of positive sample in training class is: 5478


**DECISION TREE**

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.tree import DecisionTreeClassifier


In [ ]:
dt_model= DecisionTreeClassifier(max_depth=5)

In [ ]:
dt_model.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dt_pred=dt_model.predict(x_test)

In [ ]:
dt_pred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(classification_report(y_test,dt_pred))

              precision    recall  f1-score   support

           0       0.82      0.81      0.81      3359
           1       0.53      0.55      0.54      1343

    accuracy                           0.73      4702
   macro avg       0.67      0.68      0.67      4702
weighted avg       0.73      0.73      0.73      4702



In [ ]:
print(confusion_matrix(y_test,dt_pred))

[[2709  650]
 [ 610  733]]


In [ ]:
#training error 
dt_pred_train = dt_model.predict(x_train)
accuracy_score(y_train,dt_pred_train )  


0.7340210571094331

**LOGISTIC REGRESSION** 

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
log_model=LogisticRegression(max_iter=1500)

In [ ]:
log_model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1500,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
log_pred=log_model.predict(x_test)

In [ ]:
log_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
print(classification_report(log_pred,y_test))

              precision    recall  f1-score   support

           0       0.91      0.83      0.87      3682
           1       0.53      0.69      0.60      1020

    accuracy                           0.80      4702
   macro avg       0.72      0.76      0.73      4702
weighted avg       0.82      0.80      0.81      4702



In [ ]:
print(confusion_matrix(log_pred,y_test))

[[3047  635]
 [ 312  708]]


In [ ]:
#calculate training error 
log_y_pred_train = log_model.predict(x_train) 
accuracy_score(y_train,log_y_pred_train) 

0.7994257151972775

**NAIVE BAYES MODELS**

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb_model=GaussianNB()


In [ ]:
gnb_model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
gnb_pred=gnb_model.predict(x_test)

In [ ]:
print(classification_report(y_test,gnb_pred))

              precision    recall  f1-score   support

           0       0.90      0.70      0.79      3359
           1       0.52      0.81      0.63      1343

    accuracy                           0.73      4702
   macro avg       0.71      0.75      0.71      4702
weighted avg       0.79      0.73      0.74      4702



In [ ]:
print(confusion_matrix(y_test,gnb_pred))

[[2339 1020]
 [ 259 1084]]


In [ ]:
gnb_train_pred = gnb_model.predict(x_train)
accuracy_score(y_train,gnb_train_pred)

0.7184409231096459

**RANDOM FOREST CLASSIFIER**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc_model=RandomForestClassifier(n_estimators=1000,max_leaf_nodes=50)

In [ ]:
rfc_model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=50, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rfc_pred=rfc_model.predict(x_test)

In [ ]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.78      0.99      0.87      3359
           1       0.91      0.31      0.46      1343

    accuracy                           0.79      4702
   macro avg       0.85      0.65      0.67      4702
weighted avg       0.82      0.79      0.76      4702



In [ ]:
print(confusion_matrix(y_test,rfc_pred))

[[3320   39]
 [ 927  416]]


In [ ]:
#training error 
rfc_train = rfc_model.predict(x_train)
accuracy_score(y_train,rfc_train)

0.8006487291290014

**XG BOOST**

In [ ]:
pip install xgboost 

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_model=XGBClassifier()

In [ ]:
xgb_model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
xgb_pred = xgb_model.predict(x_test)


In [ ]:
print(classification_report(y_test,xgb_pred))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89      3359
           1       0.77      0.57      0.66      1343

    accuracy                           0.83      4702
   macro avg       0.81      0.75      0.77      4702
weighted avg       0.82      0.83      0.82      4702



In [ ]:
#training error 
xgb_pred_train = xgb_model.predict(x_train) 
accuracy_score(y_train,xgb_pred_train)  

0.8540891204934595

In [ ]:
print(confusion_matrix(y_test,xgb_pred))

[[3130  229]
 [ 572  771]]
